version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "parime"
    assignees:
      - "parime"
    labels:
      - "dependencies"
      - "security"
    milestone: 0
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    pr-priority: 10

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    reviewers:
      - "parime"
    assignees:
      - "parime"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "parime"
    assignees:
      - "parime"
    labels:
      - "ci"
      - "dependencies"
    commit-message:
      prefix: "chore"
      include: "scope"
